# Generated by Django 5.0.6 on 2024-05-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordEntry',
            new_name='Postcard',
        ),
    ]
