# Generated by Django 5.0.6 on 2024-05-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_rename_passwordentry_postcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media_files/')),
                ('postcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_file', to='qr_app.postcard')),
            ],
        ),
    ]
